services:
  mcp:
    build:
      context: ./RAG
      dockerfile: Dockerfile
    ports:
      - "3111:3111"
    volumes:
      - ./uploads:/app/uploads # mount uploads folder
      - ./transaction.log:/app/transaction.log # mount transaction log file
    restart: unless-stopped
